export const projects = [
  {
    title: 'Token Management System (Company)',
    description: 'A comprehensive Token Management Application with role-based access for Companies and Normal Users. Features Firebase authentication, real-time token tracking, and Foursquare location integration.',
    technologies: ['ReactJs', 'Tailwind', 'Firebase', 'JavaScript'],
    image: '/Screenshot 01.png',
    github: 'https://github.com/Tayyabzaman1357/Company',
  },
  {
    title: 'Hospital Management System',
    description: 'A complete hospital management interface focusing on professional and trustworthy design. Highlights services, doctor profiles, and appointment booking flows.',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    image: '/Screenshot 02.png',
    live: 'https://tayyabzaman1357.github.io/Hospital-management-System/',
    github: 'https://github.com/Tayyabzaman1357/Hospital-management-System',
  },
  {
    title: 'React Quiz App',
    description: 'An interactive quiz application featuring dynamic question loading, score tracking, and smooth user interface interactions built with React.',
    technologies: ['ReactJs', 'CSS', 'JavaScript'],
    image: '/Screenshot 03.png',
    live: 'https://react-quiz-app-psi-gules.vercel.app',
    github: 'https://github.com/Tayyabzaman1357/React-Quiz-App',
  },
  {
    title: 'React Todo App',
    description: 'A clean and efficient Todo application built using React. Allows users to add, edit, complete, and manage their daily tasks seamlessly.',
    technologies: ['ReactJs', 'CSS', 'JavaScript'],
    image: '/Screenshot 04.png',
    live: 'https://react-todo-app-iota-nine.vercel.app',
    github: 'https://github.com/Tayyabzaman1357/React-Todo-App',
  },
  {
    title: 'OLX Clone with Firebase',
    description: 'A functional OLX clone featuring user authentication, product listings, and real-time database updates powered by Firebase.',
    technologies: ['HTML', 'CSS', 'JavaScript', 'Firebase'],
    image: '/Screenshot 05.png',
    live: 'https://tayyabzaman1357.github.io/Olx-firebase/',
    github: 'https://github.com/Tayyabzaman1357/Olx-firebase',
  },
  {
    title: 'SMIT Hackathon Project',
    description: 'A responsive and modern web application built during the SMIT Hackathon. Features an intuitive UI and optimized performance.',
    technologies: ['HTML', 'CSS'],
    image: '/Screenshot 06.png',
    live: 'https://tayyabzaman1357.github.io/SMIT-Hackathon/',
    github: 'https://github.com/Tayyabzaman1357/SMIT-Hackathon',
  },
  {
    title: 'Parallax Effect Website',
    description: 'A visually engaging website demonstrating smooth parallax scrolling effects and modern CSS styling techniques.',
    technologies: ['HTML', 'CSS'],
    image: '/Screenshot 07.png',
    live: 'https://tayyabzaman1357.github.io/Parallex-assigment/',
    github: 'https://github.com/Tayyabzaman1357/Parallex-assigment',
  },
  {
    title: 'Figma to Code Assignment',
    description: 'A pixel-perfect translation of a Figma design into a fully responsive HTML and CSS layout. Demonstrates strong attention to detail and modern frontend practices.',
    technologies: ['HTML', 'CSS'],
    image: '/Screenshot 08.png',
    live: 'https://tayyabzaman1357.github.io/Figma-Assigment/',
    github: 'https://github.com/Tayyabzaman1357/Figma-Assigment',
  },
  {
    title: 'Express CRUD API',
    description: 'A complete CRUD backend application built with Express and Node.js. Features modular architecture, database integration, and robust API endpoints for seamless data management.',
    technologies: ['Express', 'NodeJS', 'JavaScript'],
    image: '/Screenshot 09.png',
    live: 'https://tayyabzaman1357.github.io/Express-Crud/',
    github: 'https://github.com/Tayyabzaman1357/Express-Crud',
  }
];